### ISSUE TITLE
Programmatically Changing index using ` NavbarNotifier.index` is broken

### ISSUE THREAD

**Issue by AlexIzh** [maheshj01/navbar_router#57]
**Describe the bug**
Changing `NavbarNotifier.index` change a selected Navbar item but doesn't change a route. As result, a user sees the same page but with different selected item.

**To Reproduce**
1. Download same app
2. Add `NavbarNotifier.index = 2;` for a FAB action
3. Run the app and click on the FAB button
4. See results

**Expected behavior**
To have a way to change selected index programmatically that would actually "change" selected navigation item, not just highlight an item in the bar.

**Screenshots**
<img width="790" alt="Screenshot 2024-08-17 at 21 15 37" src="https://github.com/user-attachments/assets/292a624f-4120-4c5a-95a2-63f57a1ea6bc">

**Smartphone (please complete the following information):**
 - Device: iPhone (tested on 11 and 12, simulators and real devices), Android - Pixel 8 pro API 34 (emulator)
 - Version of the library 0.7.5

**Comment by maheshj01** [comment]
Hey @AlexIzh, Thanks for filing the issue I was able to reproduce the bug will check it out. Incase you would be interested to contribute feel free to send a PR, I would be happy to review.

**Comment by AlexIzh** [comment]
I'm able to fix this but I don't like my "quick" solution. The proper solution would requite quite a bit of refactoring to change how `index` setter works or hide it inside the module (so it won't be available outside). I will try to find a better approach and create PR

**Comment by maheshj01** [comment]
Fixed in https://github.com/maheshj01/navbar_router/pull/59 Should be available in upcoming release,

Thank you for your contribution!

**Comment by maheshj01** [comment]
released in [v0.7.6](https://pub.dev/packages/navbar_router/changelog)
